#!/bin/bash

# HG680P GPIO Wrapper
# by Lutfa Ilham
# v1.0
# GPIO Founder REYRE

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

GPIO="/sys/class/gpio"

function dual_general() {
  pin_on="${2}"
  pin_off="${3}"
  echo "${pin_on}" > "${GPIO}/export"
  echo "${pin_off}" > "${GPIO}/export"
  echo out > "${GPIO}/gpio${pin_on}/direction"
  echo out > "${GPIO}/gpio${pin_off}/direction"
  case "${1}" in
    "on")
      echo 0 > "${GPIO}/gpio${pin_off}/value"
      echo 1 > "${GPIO}/gpio${pin_on}/value"
      ;;
    "off")
      echo 0 > "${GPIO}/gpio${pin_on}/value"
      echo 1 > "${GPIO}/gpio${pin_off}/value"
      ;;
    "warn"|"dis")
      echo 1 > "${GPIO}/gpio${pin_on}/value"
      echo 1 > "${GPIO}/gpio${pin_off}/value"
      ;;
  esac
}

function power() {
  pin_power="448"
  echo "${pin_power}" > "${GPIO}/export"
  echo out > "${GPIO}/gpio${pin_power}/direction"
  case "${1}" in
    "run")
      echo 0 > "${GPIO}/gpio${pin_power}/value"
      ;;
  esac
}

function lan() {
  pin_on="418"
  pin_off="419"
  dual_general "${1}" "${pin_on}" "${pin_off}"
}

function remote_led() {
  case "${1}" in
    "on")
      echo 255 > /sys/class/leds/remote_led/brightness
      ;;
    "off")
      echo 0 > /sys/class/leds/remote_led/brightness
      ;;
    *)
      echo "Invalid argument for remote_led. Use 'on' or 'off'."
      exit 1
      ;;
  esac
}

function led1() {
  pin="448"
  echo "${pin}" > "${GPIO}/export" 2>/dev/null
  echo out > "${GPIO}/gpio${pin}/direction" 2>/dev/null
  case "${1}" in
    "on")
      echo 0 > "${GPIO}/gpio${pin}/value"
      ;;
    "off")
      echo 1 > "${GPIO}/gpio${pin}/value"
      ;;
    *)
      echo "Invalid argument for led1. Use 'on' or 'off'."
      exit 1
      ;;
  esac
}

function led_lan() {
  pin="447"
  echo "${pin}" > "${GPIO}/export" 2>/dev/null
  echo out > "${GPIO}/gpio${pin}/direction" 2>/dev/null
  case "${1}" in
    "on")
      echo 1 > "${GPIO}/gpio${pin}/value"
      ;;
    "off")
      echo 0 > "${GPIO}/gpio${pin}/value"
      ;;
    *)
      echo "Invalid argument for led_lan. Use 'on' or 'off'."
      exit 1
      ;;
  esac
}

function usage() {
  cat <<EOF
Usage:
  -power       [on, off, warn, dis, run]
  -lan         [on, off, warn, dis]
  -usb         [reset]
  -remote_led  [on, off]
  -led1        [on, off]
  -led_lan     [on, off]
EOF
}

case "${1}" in
  -power)
    power "${2}"
    ;;
  -lan)
    lan "${2}"
    ;;
  -remote_led)
    remote_led "${2}"
    ;;
  -led1)
    led1 "${2}"
    ;;
  -led_lan)
    led_lan "${2}"
    ;;
  *)
    usage
    ;;
esac
